#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           5

bspc config normal_border_color "#0A1F32"
bspc config active_border_color "#2D384A"
bspc config focused_border_color "#15416a"

bspc config presel_feedback_color "#595B82"

bspc config focus_follows_pointer true
bspc config pointer_modifier super

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a steam desktop='^10'
bspc rule -a discord desktop='^9'
bspc rule -a Spotify desktop='^9'
bspc rule -a ticktick desktop='^1'

setxkbmap -option grp:alt_shift_toggle ru,us &
sxhkd &
dunst &
$HOME/.config/polybar/launch.sh &
xset s off -dpms &
obsidian &
/home/Solalek/bin/breaker
